### ISSUE TITLE
How to install? 怎么安装啊？

### ISSUE THREAD

**Issue by ttwings** [EmmyLua/Emmy-love-api#1]
Emmylua 在intellij 上很好用，但不支持love的自动补全。 你这个怎么安装到 emmylua上面啊？

**Comment by tangzx** [comment]
下载并将api文件夹加入到你项目的 `sources root`，配合注解系统使用。
Add api files to your project and mark as sources root. Use emmy's annotation system to make auto-completion and go-definition powerful.

**Comment by ttwings** [comment]
打神，秒回。。。赞。。  注解系统里面，需要怎么注解  love.graphics.XXXX 这些也需要注解么？

**Comment by tangzx** [comment]
https://emmylua.github.io/zh_CN/annotation.html

**Comment by tangzx** [comment]
注解的使用看下文档

**Comment by ttwings** [comment]
OK ，已经全部搞定了。 很好用。  建议发到  love-awesome 上。 加大推广。  里面有个 类似的，需要 lua 插件。 没你这个好用。

**Comment by tangzx** [comment]
好的，建议不错
